### PR TITLE
kinda add clear value - fix not showing initial value - fixes #24

### LINKED ISSUE #24: Controlled input usage
The code below will cause state change loop although it's regular in [React](https://facebook.github.io/react/docs/forms.html#controlled-components) community (Ex. material-ui components)

```
onChange(value) {
  this.setState({dateValue: value});
}

render() {
  return <DatePicker value={@state.dateValue} onChange={this.onChange.bind(this)} />
}
```

### PR DESCRIPTION
**Pull request by pouriaMaleki**
Clearly it's not a real fix for this problem. Just a hack to do it, It's on contributors to accept it as a fix.

The cleaner solution is to rewrite codes that setting `prop.value` to `state.value` (and something like this for `inputValue`) make clear difference between controlled and uncontrolled component usage (and also send a warning to developer if he changed component from controlled to uncontrolled or vice versa - like they did in [material-ui components](https://github.com/callemall/material-ui)) but since it's a major change it would be better to have milestone to do.

I should say thanks guys for bringing this component open source and I try to be available if any help needed.

### CODE REVIEW

File: examples/src/components/App.js [hunk 1]
```diff
@@ -49,6 +50,23 @@ export default class App extends Component {
           </div>
           <div>
             <Example
+              title="ورود تاریخ کنترل شده"
+              code={clearDatePickerCode}
+            >
+              <DatePicker
+                value={this.state.someValue}
+                x={true}
```
Comment (mohebifar) [inline examples/src/components/App.js]: What is `x`?

**Review by mohebifar — CHANGES_REQUESTED** [review]

**Review by mohebifar — APPROVED** [review]

**Comment by mohebifar** [comment]
@pouriaMaleki Thank you! :+1:

**Comment by pouriaMaleki** [comment]
Thanks for accepting, sorry for noobish prop left in example.

**Comment by mohebifar** [comment]
Haha, that's fine.

**Comment by pouriaMaleki** [comment]
dude can you bump the version in npm?
